name: Node CI

on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout/@v3
            - name: Install Node JS 
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm test
    deployment:
        runs-on: ubuntu-latest
        needs: build-and-test
        env: 
            MONGO_URI: ${{secrets.MONGO_URI}}
        steps:
            - name: Deploy Code
              run: echo "Deploying the application Connected to db using ${{secrets.MONGO_URI}}"
        
             
              